export type Role = "SYSTEM_ADMIN" | "PARKING_MANAGER" | "PARKING_STAFF" | "PARKING_USER";

export type Permission =
  | "dashboard:view"
  | "parkingInfo:view"
  | "currentSession:view"
  | "payments:pay"
  | "payments:collect"
  | "feedback:create"
  | "vehicleTypes:manage"
  | "floors:manage"
  | "slots:manage"
  | "slots:view"
  | "slots:updateStatus"
  | "pricing:manage"
  | "sessions:manage"
  | "sessions:view"
  | "exceptions:manage"
  | "checkin:create"
  | "checkout:create"
  | "reservations:selfManage"
  | "reports:view"
  | "users:manage"
  | "settings:manage"
  | "buildings:manage"
  | "ai:view";
